service: binkio-labs-api
org: rafabinkio1
app: binkio-labs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: rafa-cto
  stage: ${opt:stage}
  region: ${opt:region}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello # https:://binkio.api/{stage}/hello
          method: get